# Generated by Django 6.0 on 2026-01-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_passwordreset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
